# Generated by Django 4.1.7 on 2023-03-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_group_course_id_alter_group_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Gruh', 'verbose_name_plural': 'Gruhlar'},
        ),
        migrations.AlterModelOptions(
            name='parents',
            options={'verbose_name': 'Ota-ona', 'verbose_name_plural': 'Ota-onalar'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name': 'Ishchi', 'verbose_name_plural': 'Ishchilar'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name': 'Mavzu', 'verbose_name_plural': 'Mavzular'},
        ),
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='parents',
            table='parents',
        ),
        migrations.AlterModelTable(
            name='staffs',
            table='staffs',
        ),
        migrations.AlterModelTable(
            name='students',
            table='students',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='subjects',
        ),
    ]
