from django.urls import path
from .views import showDemoPage,showLoginPage,doLogin,GetUserDetails,logout_user,showFirebaseJS
from .adminViews import (add_group,
    add_group_save,
    add_parent,
    add_parent_save,
    add_subject,
    admin_home,
    add_staff,
    add_staff_save,
    add_stubject_save,
    add_student,
    add_student_save,
    manage_staff,
    edit_staff,
    edit_staff_save,
    delete_staff,
    manage_parent,
    edit_parent,
    edit_parent_save,
    delete_parent,
    manage_student,
    edit_student,
    edit_student_save,
    delete_student,
    manage_subject,
    edit_subject,
    edit_subject_save,
    delete_subject,
    manage_group,
    edit_group,
    edit_group_save,
    delete_group,
    check_phone_exist,
    check_username_exist,
    parent_feedback_message,
    staff_feedback_message,
    parent_feedback_message_replied,
    staff_feedback_message_replied,
    student_leave_view,
    student_approve_leave,
    student_disapprove_leave,
    staff_leave_view,
    staff_approve_leave,
    staff_disapprove_leave,
    admin_view_attendance,
    admin_get_attendance_dates,
    admin_get_attendance_student,
    total_pending_students,
    total_active_students,
    admin_send_notification_staff,
    admin_send_notification_parent,
    send_parent_notification,
    send_staff_notification
)
from .staffViews import(
    staff_home,
    staff_take_attendance,
    get_students,
    save_attendance_data,
    staff_update_attendance,
    get_attendance_dates,
    get_attendance_student,
    save_updateattendance_data,
    staff_apply_leave,
    staff_apply_leave_save,
    staff_feedback,
    staff_feedback_save,
    staff_fcmtoken_save,
    staff_all_notification
    
)
from .parentViews import(
    parent_home,
    parent_view_attendance,
    parent_view_attendance_post,
    student_feedback_save,
    student_feedback,
    student_apply_leave_save,
    student_apply_leave,
    parent_fcmtoken_save,
    parent_all_notification
)

urlpatterns = [
    path('demo/',showDemoPage, name='demo'),
    path('', showLoginPage, name="showlogin"),
    path('get_user_details', GetUserDetails,name="get_user_details"),
    path('logout_user', logout_user,name="logoutuser"),
    path('doLogin',doLogin,name="dologin"),
    path('admin_home', admin_home,name="admin_home"),
    path('add_staff', add_staff,name="add_staff"),
    path('add_staff_save', add_staff_save,name="add_staff_save"),
    path('add_parent',add_parent,name="add_parent"),
    path('add_parent_save',add_parent_save,name="add_parent_save"),
    path('add_subject', add_subject, name="add_subject"),
    path('add_stubject_save', add_stubject_save,name="add_stubject_save"),
    path('add_student', add_student, name="add_student"),
    path('add_student_save', add_student_save,name="add_student_save"),
    path('add_group',add_group,name="add_group"),
    path('add_group_save',add_group_save,name="add_group_save"),
    path('manage_staff', manage_staff,name="manage_staff"),
    path('edit_staff/<str:staff_id>', edit_staff,name="edit_staff"),
    path('edit_staff_save', edit_staff_save,name="edit_staff_save"),
    path('delete_staff/<str:staff_id>',delete_staff,name="delete_staff"),
    path('manage_parent', manage_parent,name="manage_parent"),
    path('edit_parent/<str:parent_id>', edit_parent,name="edit_parent"),
    path('edit_parent_save', edit_parent_save,name="edit_parent_save"),
    path('delete_parent/<str:parent_id>',delete_parent,name="delete_parent"),
    path('manage_student', manage_student,name="manage_student"),
    path('edit_student/<str:student_id>', edit_student,name="edit_student"),
    path('edit_student_save', edit_student_save,name="edit_student_save"),
    path('delete_student/<int:student_id>',delete_student,name="delete_student"),
    path('manage_subject', manage_subject,name="manage_subject"),
    path('edit_subject/<str:subject_id>', edit_subject,name="edit_subject"),
    path('edit_subject_save', edit_subject_save,name="edit_subject_save"),
    path('delete_subject/<int:subject_id>',delete_subject,name="delete_subject"),
    path('manage_group',manage_group,name="manage_group"),
    path('edit_group/<str:group_id>', edit_group,name="edit_group"),
    path('edit_group_save', edit_group_save,name="edit_group_save"),
    path('delete_group/<int:group_id>',delete_group,name="delete_group"),
    path('check_phone_exist',check_phone_exist,name="check_phone_exist"),
    path('check_username_exist',check_username_exist,name="check_username_exist"),
    path('parent_feedback_message',parent_feedback_message,name="parent_feedback_message"),
    path('parent_feedback_message_replied',parent_feedback_message_replied,name="parent_feedback_message_replied"),
    path('staff_feedback_message',staff_feedback_message,name="staff_feedback_message"),
    path('staff_feedback_message_replied',staff_feedback_message_replied,name="staff_feedback_message_replied"),
    path('student_leave_view',student_leave_view,name="student_leave_view"),
    path('student_approve_leave/<str:leave_id>',student_approve_leave,name="student_approve_leave"),
    path('student_disapprove_leave/<str:leave_id>',student_disapprove_leave,name="student_disapprove_leave"),
    path('staff_leave_view',staff_leave_view,name="staff_leave_view"),
    path('staff_approve_leave/<str:leave_id>',staff_approve_leave,name="staff_approve_leave"),
    path('staff_disapprove_leave/<str:leave_id>',staff_disapprove_leave,name="staff_disapprove_leave"),
    path('admin_view_attendance',admin_view_attendance,name="admin_view_attendance"),
    path('admin_get_attendance_dates',admin_get_attendance_dates,name="admin_get_attendance_dates"),
    path('admin_get_attendance_student',admin_get_attendance_student,name="admin_get_attendance_student"),
    path('total_pending_students',total_pending_students,name="total_pending_students"),
    path('total_active_students',total_active_students,name="total_active_students"),
    path('admin_send_notification_staff',admin_send_notification_staff,name="admin_send_notification_staff"),
    path('admin_send_notification_parent',admin_send_notification_parent,name="admin_send_notification_parent"),
    path('send_parent_notification',send_parent_notification,name="send_parent_notification"),
    path('send_staff_notification',send_staff_notification,name="send_staff_notification"),

    #Staffs
    path('staff_home',staff_home,name="staff_home"),
    path('staff_take_attendance',staff_take_attendance,name="staff_take_attendance"),
    path('staff_update_attendance',staff_update_attendance,name="staff_update_attendance"),
    path('get_students',get_students,name="get_students"),
    path('save_attendance_data',save_attendance_data,name="save_attendance_data"),
    path('save_updateattendance_data',save_updateattendance_data,name="save_updateattendance_data"),
    path('get_attendance_dates',get_attendance_dates,name="get_attendance_dates"),
    path('get_attendance_student',get_attendance_student,name="get_attendance_student"),
    path('staff_apply_leave',staff_apply_leave,name="staff_apply_leave"),
    path('staff_apply_leave_save',staff_apply_leave_save,name="staff_apply_leave_save"),
    path('staff_feedback',staff_feedback,name="staff_feedback"),
    path('staff_feedback_save',staff_feedback_save,name="staff_feedback_save"),
    path('staff_fcmtoken_save',staff_fcmtoken_save,name="staff_fcmtoken_save"),
    path('staff_all_notification',staff_all_notification,name="staff_all_notification"),


    #Parents
    path('parent_home',parent_home,name="parent_home"),
    path('parent_view_attendance',parent_view_attendance,name="parent_view_attendance"),
    path('parent_view_attendance_post',parent_view_attendance_post,name="parent_view_attendance_post"),
    path('student_apply_leave',student_apply_leave,name="student_apply_leave"),
    path('student_apply_leave_save',student_apply_leave_save,name="student_apply_leave_save"),
    path('student_feedback',student_feedback,name="student_feedback"),
    path('student_feedback_save',student_feedback_save,name="student_feedback_save"),
    path('parent_fcmtoken_save',parent_fcmtoken_save,name="parent_fcmtoken_save"),
    path('parent_all_notification',parent_all_notification,name="parent_all_notification"),

    path('firebase-messaging-sw.js',showFirebaseJS,name="show_firebase_js")

]